### ISSUE TITLE
Substitute Net::Proxmox::VE with libpve-apiclient-perl

### ISSUE THREAD

**Issue by vahem2lu** [henyxia/proxmox2netbox#1]
Hi! Is this still maintained, do you have any interest patching it and use new API client?

**Comment by henyxia** [comment]
Hi!
I still wish maintain it, I will look for this update this week end :)

**Comment by henyxia** [comment]
As the previous lib was still working, I choose to duplicate the script into a new one using the Proxmox library.
Enjoy :)
