### ISSUE TITLE
Add support for not to verify SSL cert

### ISSUE THREAD

**Issue by vahem2lu** [henyxia/proxmox2netbox#2]
Not an "issue" though, but for those who would like to access API directly from CLI and not via SSL certs
add to your code
section
```
 my $conn = PVE::APIClient::LWP->new(
/---/
    ssl_opts => {
        verify_hostname => 0,
    },
```

**Comment by henyxia** [comment]
Done!
Do not hesitate to open a PR directly if you want to ;)
